import { siteConfigV1Schema } from './site-config-v1.schema.js';

const v1Properties = siteConfigV1Schema.properties;
const heroSectionSchema = v1Properties.sections.items.oneOf[0];
const safeTextSchema = heroSectionSchema.properties.overline;
const richTextSchema = heroSectionSchema.properties.title;
const identifierSchema = heroSectionSchema.properties.id;
const sectionBaseProperties = {
  id: identifierSchema,
  order: heroSectionSchema.properties.order,
  visible: heroSectionSchema.properties.visible,
  anchor: heroSectionSchema.properties.anchor,
} as const;
const sectionBaseRequired = ['id', 'type', 'variant', 'order', 'visible', 'anchor'] as const;
const pageSeoSchema = v1Properties.projects.items.properties.seo;

export const siteConfigV2Schema = {
  type: 'object',
  required: [
    'schemaVersion',
    'releaseId',
    'publishedAt',
    'locale',
    'identity',
    'seo',
    'theme',
    'uiLabels',
    'media',
    'header',
    'navigationItems',
    'portfolioCategories',
    'projects',
    'footer',
    'contact',
    'pages',
  ],
  properties: {
    schemaVersion: { type: 'integer', const: 2 },
    releaseId: v1Properties.releaseId,
    publishedAt: v1Properties.publishedAt,
    locale: v1Properties.locale,
    identity: v1Properties.identity,
    seo: v1Properties.seo,
    theme: v1Properties.theme,
    uiLabels: v1Properties.uiLabels,
    media: v1Properties.media,
    header: v1Properties.header,
    navigationItems: v1Properties.navigationItems,
    portfolioCategories: v1Properties.portfolioCategories,
    projects: v1Properties.projects,
    footer: v1Properties.footer,
    contact: {
      type: 'object',
      required: [
        'email',
        'phoneLabel',
        'phoneE164',
        'instagramUrl',
        'whatsappNumber',
        'whatsappDefaultMessage',
      ],
      properties: {
        email: v1Properties.seo.properties.organization.properties.email,
        phoneLabel: safeTextSchema,
        phoneE164: { type: 'string', pattern: '^\\+[1-9][0-9]{7,14}$' },
        instagramUrl: {
          type: 'string',
          format: 'uri',
          maxLength: 2_048,
          pattern: '^https://(?:www\\.)?instagram\\.com(?:/|$)',
        },
        whatsappNumber: { type: 'string', pattern: '^[1-9][0-9]{7,14}$' },
        whatsappDefaultMessage: safeTextSchema,
      },
      additionalProperties: false,
    },
    pages: {
      type: 'array',
      minItems: 1,
      maxItems: 100,
      items: {
        type: 'object',
        required: ['id', 'slug', 'path', 'order', 'visible', 'seo', 'sections'],
        properties: {
          id: identifierSchema,
          slug: identifierSchema,
          path: {
            type: 'string',
            minLength: 1,
            maxLength: 66,
            pattern: '^/(?:[a-z0-9][a-z0-9-]*)?$',
          },
          order: { type: 'integer', minimum: 0, maximum: 100_000 },
          visible: { type: 'boolean' },
          seo: pageSeoSchema,
          sections: {
            type: 'array',
            minItems: 1,
            maxItems: 30,
            items: {
              oneOf: [
                heroSectionSchema,
                {
                  type: 'object',
                  required: [
                    ...sectionBaseRequired,
                    'overline',
                    'title',
                    'description',
                    'nameLabel',
                    'emailLabel',
                    'phoneLabel',
                    'subjectLabel',
                    'messageLabel',
                    'submitLabel',
                    'successMessage',
                    'errorMessage',
                    'privacyNotice',
                  ],
                  properties: {
                    ...sectionBaseProperties,
                    type: { const: 'contact-form' },
                    variant: { const: 'default-v1' },
                    overline: safeTextSchema,
                    title: richTextSchema,
                    description: {
                      type: 'array',
                      minItems: 1,
                      maxItems: 20,
                      items: safeTextSchema,
                    },
                    nameLabel: safeTextSchema,
                    emailLabel: safeTextSchema,
                    phoneLabel: safeTextSchema,
                    subjectLabel: safeTextSchema,
                    messageLabel: safeTextSchema,
                    submitLabel: safeTextSchema,
                    successMessage: safeTextSchema,
                    errorMessage: safeTextSchema,
                    privacyNotice: safeTextSchema,
                  },
                  additionalProperties: false,
                },
                {
                  type: 'object',
                  required: [
                    ...sectionBaseRequired,
                    'overline',
                    'title',
                    'description',
                    'projectIds',
                    'maxColumns',
                  ],
                  properties: {
                    ...sectionBaseProperties,
                    type: { const: 'project-grid' },
                    variant: { const: 'grid-v1' },
                    overline: safeTextSchema,
                    title: richTextSchema,
                    description: {
                      type: 'array',
                      minItems: 1,
                      maxItems: 20,
                      items: safeTextSchema,
                    },
                    projectIds: {
                      type: 'array',
                      maxItems: 1_000,
                      uniqueItems: true,
                      items: identifierSchema,
                    },
                    maxColumns: { type: 'integer', minimum: 1, maximum: 4 },
                  },
                  additionalProperties: false,
                },
                {
                  type: 'object',
                  required: [
                    ...sectionBaseRequired,
                    'overline',
                    'title',
                    'body',
                    'label',
                    'message',
                  ],
                  properties: {
                    ...sectionBaseProperties,
                    type: { const: 'whatsapp-cta' },
                    variant: { const: 'editorial-v1' },
                    overline: safeTextSchema,
                    title: richTextSchema,
                    body: {
                      type: 'array',
                      minItems: 1,
                      maxItems: 20,
                      items: safeTextSchema,
                    },
                    label: safeTextSchema,
                    message: safeTextSchema,
                  },
                  additionalProperties: false,
                },
              ],
            },
          },
        },
        additionalProperties: false,
      },
    },
  },
  additionalProperties: false,
} as const;
